name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore LumaTray.sln

    - name: Build
      run: dotnet build LumaTray.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: dotnet publish LumaTray.csproj --configuration ${{ matrix.configuration }} --runtime win-x64 --self-contained false --output ./publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: LumaTray-${{ matrix.configuration }}
        path: ./publish
